version: "3"

services:
  mongo:
    image: mongo
    #ports:
    #  - 27017:27017
    networks:
      - back
    restart: always

  bitcoind:
    image: lukechilds/bitcoind
    #ports:
    #  - 18332:18332
    volumes:
      - $HOME/cyphernode/bitcoin/:/data/.bitcoin
    networks:
      - back
    restart: always

  bitcoindwrapper:
    build: .
    depends_on:
      - mongo
    image: bitcoincliwrapper
    ports:
      - 3000:3000
    networks:
      - back
      - front
    restart: always

networks:
  back:
    external: true
  front:
    external: true
