version: "3"

services:
  mongo:
    image: mongo
    #ports:
    #  - 27017:27017
    networks:
      - back
    restart: always

  bitcoind:
    image: lukechilds/bitcoind
    #ports:
    #  - 18332:18332
    volumes:
      - $HOME/cyphernode/bitcoin/:/data/.bitcoin
    networks:
      - back
    restart: always

  bitcoindwrapper:
    build: .
    depends_on:
      - mongo
      #- bitcoind
    image: bitcoindwrapper
    ports:
      - 3000:3000
    networks:
      - back
      - front
    restart: always

  bitcoindwrapperexplorer:
    image: swaggerapi/swagger-ui
    depends_on:
      - bitcoindwrapper
    environment:
      - PORT=3001
      - SWAGGER_JSON=/data/openapi.json
      - BASE_URL=/explorer
      # - API_URL=http://localhost:3000/openapi.json
    ports:
      - 3001:3001
    volumes:
      - $HOME/blockchain/bitcoincli-wrapper/explorer/:/data
    networks:
      - front
    restart: always

networks:
  back:
    external: true
  front:
    external: true
